### ISSUE TITLE
Gcc error

### ISSUE THREAD

**Issue by lujiajing1126** [orca-zhang/influxdb-c#1]
For GCC compiler, there should be a pair of parenthesis around the type

For example: 

`(size_t)(-1)` instead of `size_t(-1)`

**Comment by orca-zhang** [comment]
Hi, I've noticed your feedback.

So, is compile error occurred when using `INFLUX_*` macros?

**Comment by orca-zhang** [comment]
I've fixed it.

Thank you for your feedback again.

Look forward to your further suggestions.
